name: Build legate.core
on: 
  push:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
  pull_request:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
env:
  COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
  PROJECT: github-core-ci
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run CI
        run: |
          if [[ ! -d legate-ci ]]
          then
            git clone ssh://git@gitlab-master.nvidia.com:12051/legate/legate-ci.git
          else
            cd legate-ci
            git pull
            cd ..
          fi
          cd legate-ci
          cd github-ci/
          cd legate.core
          rm -rf ngc-artifacts
          ./build.sh > ${COMMIT}.log 2>&1
          cat *artifacts/*/*
